notifications template
openclassify/openclassify pull request #1019
Opened 2021-04-03 16:40 UTC by spektra2147

2021-04-04 11:31 UTC, fatihalp commented on addons/default/visiosoft/advs-module/src/Notifications/AdvsModuleNotificationsTemplateSeeder.php
> +                        'message' => '<p><strong>&nbsp;Your post <a href="{url}" target="_blank">{name}</a> has been created successfully.</strong></p>',
&nbsp; ?

2021-04-04 11:32 UTC, fatihalp commented on addons/default/visiosoft/profile-module/src/Notifications/ProfileModuleNotificationsTemplateSeeder.php
> +                                                                 <p style="color: #707070; font-size: 16px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
Please remove all lorem ipsum

2021-04-04 11:32 UTC, fatihalp requested changes
delete lorem ipsum

2021-04-06 12:31 UTC, fatihalp commented on addons/default/visiosoft/profile-module/src/Notifications/ProfileModuleNotificationsTemplateSeeder.php
> +    public function createTemplate($params)
move it @spektra2147

2021-04-06 12:35 UTC, diashalabi requested changes

2021-04-06 12:35 UTC, diashalabi commented on addons/default/visiosoft/advs-module/src/Notifications/AdvsModuleNotificationsTemplateSeeder.php
> +                $this->createTemplate($template);
dispatch

2021-04-07 15:14 UTC, diashalabi approved these changes

2021-04-09 07:45 UTC, merged