need to items in cart for new oc-theme
openclassify/openclassify pull request #1056
Opened 2021-04-23 15:03 UTC by muammertop

2021-04-23 15:24 UTC, fatihalp commented on addons/default/visiosoft/advs-module/src/Http/Controller/AdvsController.php
>              $response['status'] = "success";
better to remove addtocart near feature

2021-04-23 15:24 UTC, fatihalp approved these changes

2021-04-26 09:04 UTC, diashalabi requested changes

2021-04-26 09:04 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/views/ad-detail/partials/detail.twig
> +        {{ setting_value('visiosoft.module.advs::show_price_to_members_only') ? (auth_check() ? false : 'd-none') : false }}">
`{{ setting_value('visiosoft.module.advs::show_price_to_members_only') ? (not auth_check() ? 'd-none')  }}`

2021-04-26 09:42 UTC, diashalabi approved these changes

2021-04-26 09:42 UTC, merged