#3284 Add description area in all modules on admin panel
openclassify/openclassify pull request #1085
Opened 2021-05-22 10:48 UTC by muammertop

2021-05-23 13:22 UTC, spektra2147 approved these changes

2021-05-26 07:03 UTC, diashalabi requested changes

2021-05-26 07:03 UTC, diashalabi commented on addons/default/visiosoft/defaultadmin-theme/resources/views/layouts/default.twig
> +        {% endif %}
you can use the example found here /admin/system/dumps you don't need to create a new div

2021-05-27 11:25 UTC, diashalabi approved these changes

2021-05-27 11:25 UTC, merged