detail page
openclassify/openclassify pull request #1169
Opened 2021-09-21 15:21 UTC by spektra2147

2021-09-22 06:23 UTC, muammertop approved these changes

2021-09-23 11:40 UTC, fatihalp commented on addons/default/visiosoft/base-theme/resources/css/bootstrap-notify-visio.css
> +    z-index: 99999999999999;
99999999999999 ? @spektra2147

2021-09-24 06:31 UTC, fatihalp requested changes
99999999999999 ? @spektra2147

2021-09-28 09:30 UTC, diashalabi approved these changes

2021-09-28 09:41 UTC, merged