#1945 Post ad - location section
openclassify/openclassify pull request #1181
Opened 2021-10-01 09:42 UTC by muammertop

2021-10-01 09:43 UTC, muammertop commented
![image](https://user-images.githubusercontent.com/22885454/135599820-f4b7a31c-8845-4ec5-9d82-822b4bc72a40.png)

2021-10-01 09:44 UTC, diashalabi requested changes

2021-10-01 09:44 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/views/new-ad/map.twig
> +    .location-map .tab-content select { border-color: #e8e8e8; border-radius: 3px; }
inline styles?

2021-10-04 06:59 UTC, spektra2147 approved these changes

2021-10-04 07:54 UTC, fatihalp approved these changes

2021-10-04 12:04 UTC, diashalabi approved these changes

2021-10-04 12:04 UTC, merged