fix
openclassify/openclassify pull request #1236
Opened 2021-11-29 13:37 UTC by YosefGul

2021-11-29 13:52 UTC, spektra2147 approved these changes

2021-11-29 13:58 UTC, muammertop requested changes

2021-11-29 13:58 UTC, muammertop commented on addons/default/visiosoft/advs-module/resources/views/list/gallery.twig
> -                                {{ addBlock('list/extra-actions', {'ad': adv, 'vars': _context}, ['favs', 'comparisons'])|raw }}
revert to addblock

2021-11-29 13:58 UTC, muammertop commented on addons/default/visiosoft/advs-module/resources/views/list/gallery.twig
> +                                    <span>TL</span>
change to dynamic currency

2021-12-02 07:50 UTC, fatihalp requested changes
revert to addblock
change to dynamic currency

2021-12-02 07:51 UTC, fatihalp commented
how you approved @spektra2147

2021-12-06 07:52 UTC, muammertop commented on composer.json
> -        "anomaly/installer-module": "~2.4.0"
revert to installer-module pls

2021-12-06 07:52 UTC, muammertop commented on addons/default/visiosoft/base-theme/resources/css/theme.css
> +.tl-span {
where are you use this?

2021-12-06 08:15 UTC, muammertop approved these changes

2021-12-06 09:25 UTC, diashalabi commented
I don't think it's a good idea to pull from interns @fatihalp Let's close this pull request as there are many things missing like the doping classes. This will affect all the customers who use openclassify, there is no margin for error in this repo :wink:

2021-12-06 12:43 UTC, diashalabi requested changes

2021-12-06 12:43 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/views/list/gallery.twig
> -            <div class="w-50 gallery-item-wrapper mb-1{{ adv.doping != null ? ' doping_type4' }}">
Why did you remove the doping check?

2021-12-06 12:43 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/views/list/gallery.twig
> +                                <a href="{{ adv.detail_url }}" class="product-name-hb text-dark">{{ adv.cat1_name }} /{{ adv.cat2_name }}</a>
`<a>` tags should not be used inside `<a>` tags, please test before sending pull requests

2021-12-06 12:43 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/views/list/gallery.twig
> -                            <a href="{{ adv.detail_url }}">{{ adv.name }}</a>
Why removed the ad name?

2021-12-07 15:53 UTC, fatihalp approved these changes

2021-12-07 15:53 UTC, merged