change Exception
openclassify/openclassify pull request #1243
Opened 2021-12-06 12:37 UTC by spektra2147

2021-12-06 12:44 UTC, fatihalp approved these changes

2021-12-06 12:44 UTC, fatihalp requested changes
Turkish? @spektra2147

2021-12-06 13:11 UTC, diashalabi approved these changes

2021-12-06 13:59 UTC, profstyle1 approved these changes

2021-12-06 13:59 UTC, profstyle1 approved these changes

2021-12-07 09:48 UTC, fatihalp approved these changes

2021-12-07 09:48 UTC, merged