#4865 optional seller information setting
openclassify/openclassify pull request #1244
Opened 2021-12-07 08:33 UTC by muammertop

2021-12-07 09:09 UTC, diashalabi approved these changes

2021-12-07 09:10 UTC, diashalabi requested changes

2021-12-07 09:10 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/config/settings/settings.php
> +        'required' => true,
Why required?

2021-12-07 09:10 UTC, diashalabi commented on addons/default/visiosoft/advs-module/resources/lang/en/setting.php
> +        'instructions' => 'Hiding to seller infos by selected main categories in ads detail page',
Improve translation please :wink:

2021-12-07 13:40 UTC, diashalabi approved these changes

2021-12-08 07:30 UTC, profstyle1 approved these changes

2021-12-08 07:30 UTC, merged