#5107 Asfaltdunyası mobile
openclassify/openclassify pull request #1261
Opened 2022-01-06 14:31 UTC by diashalabi

2022-01-06 14:33 UTC, muammertop approved these changes

2022-01-06 14:48 UTC, fatihalp commented
lets make it clean by removing mobile-list.twig

creating issue and then merge it

2022-01-06 14:48 UTC, fatihalp requested changes
remove mobile & better ui 
created issue

2022-01-07 06:46 UTC, fatihalp approved these changes
merging then lets clean it

2022-01-07 06:46 UTC, merged