Docker
openclassify/openclassify pull request #1316
Opened 2022-06-09 06:47 UTC by MostafaMoradii

2022-06-09 06:49 UTC, muammertop approved these changes

2022-06-09 10:05 UTC, MostafaMoradii commented on composer.json
> +        "laravel/horizon": "^5.9"
No

2022-06-09 10:06 UTC, fatihalp commented
This branch has conflicts that must be resolved
@MostafaMoradii

2022-06-10 06:42 UTC, muammertop requested changes

2022-06-10 06:42 UTC, muammertop commented on docker-compose.yml
> +        image: sail-7.4/drifter
drifter?

2022-06-15 08:16 UTC, muammertop approved these changes

2022-06-20 19:21 UTC, fatihalp approved these changes

2022-06-21 15:07 UTC, spektra2147 approved these changes

2022-06-21 15:07 UTC, merged