add export users module
openclassify/openclassify pull request #658
Opened 2020-09-08 16:34 UTC by spektra2147

@ozcan-durak

2020-09-08 17:05 UTC, diashalabi requested changes

2020-09-08 17:05 UTC, diashalabi commented on addons/default/visiosoft/profile-module/resources/lang/en/button.php
> +    'export' => 'Export CSV',
If someone wants to use the export translation as "Export" what will he name it then? Please name the translation according to the translated text. For example "export_csv"

2020-09-09 06:21 UTC, diashalabi approved these changes

2020-09-09 06:53 UTC, fatihalp approved these changes

2020-09-09 07:54 UTC, merged