added sorting optional for location
openclassify/openclassify pull request #775
Opened 2020-11-04 10:44 UTC by spektra2147

2020-11-04 12:00 UTC, diashalabi requested changes

2020-11-04 12:00 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/config/settings/settings.php
> +                'order' => 'order'
trans?

2020-11-04 12:00 UTC, diashalabi commented on addons/default/visiosoft/location-module/src/Http/Controller/AjaxController.php
> +
DRY

2020-11-05 07:58 UTC, spektra2147 commented on addons/default/visiosoft/location-module/resources/config/settings/settings.php
> +                'order' => 'order'
These are the column names

2020-11-05 07:59 UTC, spektra2147 commented on addons/default/visiosoft/location-module/src/Http/Controller/AjaxController.php
> +
OK. I can do a function.

2020-11-05 08:05 UTC, diashalabi approved these changes

2020-11-05 09:24 UTC, muammertop approved these changes

2020-11-05 09:37 UTC, merged