admin theme && fixed version excel export libs
openclassify/openclassify pull request #784
Opened 2020-11-09 11:43 UTC by spektra2147

2020-11-09 12:03 UTC, diashalabi requested changes

2020-11-09 12:03 UTC, diashalabi commented on addons/default/visiosoft/cats-module/resources/views/table/table.twig
> +                        <li class="breadcrumb-item"><a><b>{{ parnt }}</b></a></li>
no need for an `<a>` tag here

2020-11-09 13:46 UTC, diashalabi commented on addons/default/visiosoft/cats-module/resources/views/table/table.twig
> +                        <i class="fa fa-arrow-left"></i> Go To Parent
trans

2020-11-09 13:50 UTC, diashalabi approved these changes

2020-11-10 13:50 UTC, muammertop approved these changes

2020-11-10 13:52 UTC, diashalabi approved these changes

2020-11-10 13:52 UTC, merged