#2279 country selection with flags & location table columns changed
openclassify/openclassify pull request #836
Opened 2020-11-30 08:57 UTC by muammertop

2020-11-30 10:38 UTC, diashalabi requested changes

2020-11-30 10:38 UTC, diashalabi commented on addons/default/visiosoft/location-module/migrations/2020_11_27_124940_visiosoft.module.location__add_abv_country.php
> +}
why do we have 2 of the same migration?

2020-11-30 10:38 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/js/filterLocation.js
> +                    console.log(value)
log?

2020-11-30 10:38 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/views/ads-list/partials/location-fields.twig
> +    var flag_img = "{{ img('visiosoft.module.location::images/flags.png').url|raw }}"
are we using this variable?

2020-11-30 11:16 UTC, muammertop commented on addons/default/visiosoft/location-module/migrations/2020_11_27_124940_visiosoft.module.location__add_abv_country.php
> +}
I removed the other one

2020-11-30 11:16 UTC, muammertop commented on addons/default/visiosoft/location-module/migrations/2020_11_27_124940_visiosoft.module.location__add_abv_country.php
> +}
I removed the other one @diashalabi

2020-11-30 11:17 UTC, muammertop commented on addons/default/visiosoft/location-module/resources/views/ads-list/partials/location-fields.twig
> +    var flag_img = "{{ img('visiosoft.module.location::images/flags.png').url|raw }}"
kaldırıldı

2020-11-30 11:18 UTC, muammertop commented on addons/default/visiosoft/location-module/resources/js/filterLocation.js
> +                    console.log(value)
kaldırıldı

2020-11-30 14:54 UTC, fatihalp approved these changes

2020-12-01 08:55 UTC, spektra2147 commented on addons/default/visiosoft/location-module/resources/js/filterLocation.js
> +                    console.log(value)
remove

2020-12-01 09:00 UTC, muammertop commented on addons/default/visiosoft/location-module/resources/js/filterLocation.js
> +            // $('.filter-location-modal,.filter-location-back,.filter-location-modal .countries').hide();
removed

2020-12-01 09:53 UTC, diashalabi requested changes

2020-12-01 09:53 UTC, diashalabi commented on addons/default/visiosoft/advs-module/src/Adv/AdvModel.php
> +        $seo = str_slug($object->getObject()->name, '-');
$object->getObject()->name can you make it slug

2020-12-01 09:53 UTC, diashalabi commented on addons/default/visiosoft/location-module/migrations/2020_10_13_133916_visiosoft.module.location__add_abv_to_countries.php
> +	];
why do we have 2 of the same migration?

2020-12-01 12:22 UTC, diashalabi approved these changes

2020-12-01 12:23 UTC, merged