maden bug fixed on slack channel
openclassify/openclassify pull request #878
Opened 2020-12-23 08:58 UTC by muammertop

2020-12-23 09:38 UTC, diashalabi requested changes

2020-12-23 09:38 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/views/ads-list/partials/location-fields.twig
> +            <div>asd</div>
you forgot this part

2020-12-23 09:38 UTC, diashalabi commented on addons/default/visiosoft/location-module/resources/js/filterLocation.js
> +            ' type="checkbox" data-field="' + field_name + '" data-id="' + id + '" '+ selected +'>\n' +
too many spaces 🙂

2020-12-24 07:20 UTC, diashalabi requested changes

2020-12-24 07:20 UTC, diashalabi commented on addons/default/visiosoft/advs-module/src/Adv/Table/AdvTableColumns.php
> +use function foo\func;
?

2020-12-24 09:04 UTC, spektra2147 approved these changes

2020-12-24 09:06 UTC, merged