fixed maintenance mode
openclassify/openclassify pull request #884
Opened 2020-12-28 09:38 UTC by spektra2147

@diashalabi 
config ('streams :: maintenance.enabled') value setting updated after listener.

2020-12-28 09:45 UTC, diashalabi approved these changes

2020-12-28 13:13 UTC, diashalabi requested changes

2020-12-28 13:13 UTC, diashalabi commented on addons/default/visiosoft/advs-module/src/Adv/Table/AdvTableBuilder.php
> +        ],
you only used this javascript for the advanced, why don't you only add it for the advanced type?

2020-12-29 15:01 UTC, diashalabi approved these changes

2020-12-29 15:03 UTC, fatihalp approved these changes

2020-12-29 15:03 UTC, merged