alibaba-theme is_buying area review
openclassify/openclassify pull request #939
Opened 2021-02-05 09:18 UTC by muammertop

2021-02-08 06:56 UTC, spektra2147 commented on addons/default/visiosoft/defaultadmin-theme/resources/js/alibaba/buyingSelling.js
> +        console.log(is_buying)
console

2021-02-08 10:00 UTC, spektra2147 approved these changes

2021-02-08 11:06 UTC, fatihalp approved these changes

2021-02-08 11:12 UTC, diashalabi approved these changes

2021-02-08 11:12 UTC, diashalabi commented on addons/default/visiosoft/defaultadmin-theme/src/DefaultadminThemeServiceProvider.php
> +	    }
is there no better way?

2021-02-08 11:12 UTC, diashalabi commented on addons/default/visiosoft/defaultadmin-theme/resources/views/admin/settings/form/partials/default.twig
> +        pick_option = "{{ trans('visiosoft.theme.alibaba::field.pick_option.name') }}"
why do we have alibaba here?

2021-02-08 11:12 UTC, diashalabi commented on addons/default/visiosoft/defaultadmin-theme/resources/js/alibaba/buyingSelling.js
> +}
why do we have alibaba here?

2021-02-08 13:25 UTC, fatihalp requested changes
remove theme spesific code

2021-02-08 14:57 UTC, diashalabi requested changes

2021-02-08 14:57 UTC, diashalabi commented on addons/default/visiosoft/profile-module/resources/config/settings/sections.php
> +	                'register_corporate_protection_url',
this setting should be in the store module

2021-02-08 14:57 UTC, diashalabi commented on addons/default/visiosoft/profile-module/resources/config/settings/settings.php
> +	],
this setting should be in the store module

2021-02-08 14:57 UTC, diashalabi commented on addons/default/visiosoft/profile-module/resources/lang/en/setting.php
> +	],
this setting should be in the store module

2021-02-09 10:15 UTC, diashalabi requested changes

2021-02-09 10:15 UTC, diashalabi commented on addons/default/visiosoft/base-theme/resources/views/partials/assets.twig
> +{{ asset_script("theme.js") }}
why remove min?

2021-02-09 10:15 UTC, diashalabi commented on addons/default/visiosoft/base-theme/resources/views/partials/metadata.twig
> +{{ asset_style("theme.css") }}
why remove min?

2021-02-09 10:30 UTC, muammertop commented on addons/default/visiosoft/base-theme/resources/views/partials/assets.twig
> +{{ asset_script("theme.js") }}
because not compiling @fatihalp

2021-02-09 10:30 UTC, muammertop commented on addons/default/visiosoft/base-theme/resources/views/partials/metadata.twig
> +{{ asset_style("theme.css") }}
because not compiling

2021-02-09 13:07 UTC, diashalabi approved these changes

2021-02-09 13:09 UTC, fatihalp approved these changes

2021-02-09 13:09 UTC, merged